export const prePackagedCollection = [
  {
    id: 1,
    name: 'Corine Land Cover 2012',
    source: 'Pre-packaged',
    area: 'NUTS 3 Bizkaia',
    year: 2018,
    resolution: '100m',
    type: 'Raster',
    format: 'GeoTiff',
    version: 'v2020_20u1',
    size: '125.0 MB',
    warning: '',
  },
  {
    id: 2,
    name: 'Corine Land Cover 2018',
    source: 'Pre-packaged',
    area: '',
    year: 2018,
    resolution: '100m',
    type: 'Vector',
    format: 'ESRI Geodatabase',
    version: 'v2020_20u1',
    size: '5.0 GB',
    warning: '',
  },
  {
    id: 3,
    name: 'Land Cover 2021',
    source: 'Map viewer',
    area: 'Rectangle area',
    year: 2018,
    resolution: '100m',
    type: 'Vector',
    format: 'SQLite Geodatabase',
    version: 'v2020_20u1',
    size: '3.5 GB',
    warning: 'This is a warning text',
  },
];
